/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ChromaKeyPlugin,
  extensionToMime: () => extensionToMime
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  targetColor: "#FFFFFF",
  tolerance: 30,
  autoDetectColor: true,
  edgeSoftening: true,
  invertColors: false,
  chromaFolderPath: "chroma"
};
var IMAGE_EXTENSIONS = [
  "png",
  "jpg",
  "jpeg",
  "gif",
  "bmp",
  "webp"
];

// src/settings.ts
var import_obsidian = require("obsidian");
var ChromaKeySettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("p", {
      text: 'These settings are used as defaults when you right-click an image and select "remove background".',
      cls: "setting-item-description"
    });
    new import_obsidian.Setting(containerEl).setName("Auto-detect background color").setDesc(
      "Sample the top-left pixel of the image to determine the background color. Turn off to use a fixed target color."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoDetectColor).onChange(async (value) => {
        this.plugin.settings.autoDetectColor = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (!this.plugin.settings.autoDetectColor) {
      new import_obsidian.Setting(containerEl).setName("Target color").setDesc(
        "The background color to remove (hex format, e.g. #Ffffff for white)."
      ).addText(
        (text) => text.setPlaceholder("#Ffffff").setValue(this.plugin.settings.targetColor).onChange(async (value) => {
          const cleaned = value.trim();
          if (/^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$/.test(cleaned)) {
            this.plugin.settings.targetColor = cleaned;
            await this.plugin.saveSettings();
          }
        })
      );
    }
    new import_obsidian.Setting(containerEl).setName("Default tolerance").setDesc(
      "Default color distance threshold for the processing modal (0 = exact match, 100 = very aggressive)."
    ).addSlider(
      (slider) => slider.setLimits(0, 100, 1).setValue(this.plugin.settings.tolerance).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.tolerance = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Edge softening").setDesc(
      "Apply smooth alpha blending at the edges of the removed background for cleaner results."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.edgeSoftening).onChange(async (value) => {
        this.plugin.settings.edgeSoftening = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Invert colors").setDesc(
      "Invert the colors of visible pixels after background removal."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.invertColors).onChange(async (value) => {
        this.plugin.settings.invertColors = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/chroma-key.ts
function hexToRgb(hex) {
  let cleaned = hex.replace("#", "");
  if (cleaned.length === 3) {
    cleaned = cleaned[0] + cleaned[0] + cleaned[1] + cleaned[1] + cleaned[2] + cleaned[2];
  }
  const num = parseInt(cleaned, 16);
  return {
    r: num >> 16 & 255,
    g: num >> 8 & 255,
    b: num & 255
  };
}
function colorDistance(a, b) {
  const dr = a.r - b.r;
  const dg = a.g - b.g;
  const db = a.b - b.b;
  return Math.sqrt(dr * dr + dg * dg + db * db);
}
function loadImageFromBlob(blob) {
  return new Promise((resolve, reject) => {
    const url = URL.createObjectURL(blob);
    const img = new Image();
    img.onload = () => {
      URL.revokeObjectURL(url);
      resolve(img);
    };
    img.onerror = (_e) => {
      URL.revokeObjectURL(url);
      reject(new Error("Failed to load image"));
    };
    img.src = url;
  });
}
function canvasToArrayBuffer(canvas) {
  return new Promise((resolve, reject) => {
    canvas.toBlob((blob) => {
      if (!blob) {
        reject(new Error("Canvas toBlob returned null"));
        return;
      }
      blob.arrayBuffer().then(resolve, reject);
    }, "image/png");
  });
}
function applyChromaKey(imageData, settings) {
  const data = imageData.data;
  let target;
  if (settings.autoDetectColor) {
    target = {
      r: data[0],
      g: data[1],
      b: data[2]
    };
  } else {
    target = hexToRgb(settings.targetColor);
  }
  const pixelCount = data.length / 4;
  const maxDistance = 441.67;
  const threshold = settings.tolerance / 100 * maxDistance;
  const softStart = threshold * 0.7;
  for (let i = 0; i < pixelCount; i++) {
    const offset = i * 4;
    const pixel = {
      r: data[offset],
      g: data[offset + 1],
      b: data[offset + 2]
    };
    const dist = colorDistance(pixel, target);
    if (dist < softStart) {
      data[offset + 3] = 0;
    } else if (settings.edgeSoftening && dist < threshold) {
      const originalAlpha = data[offset + 3];
      const factor = (dist - softStart) / (threshold - softStart);
      data[offset + 3] = Math.round(originalAlpha * factor);
    }
  }
  if (settings.invertColors) {
    for (let i = 0; i < pixelCount; i++) {
      const offset = i * 4;
      if (data[offset + 3] > 0) {
        data[offset] = 255 - data[offset];
        data[offset + 1] = 255 - data[offset + 1];
        data[offset + 2] = 255 - data[offset + 2];
      }
    }
  }
}
function processImageElement(img, settings) {
  const canvas = activeDocument.createElement("canvas");
  canvas.width = img.width;
  canvas.height = img.height;
  const ctx = canvas.getContext("2d");
  if (!ctx) {
    throw new Error("Could not get 2D canvas context");
  }
  ctx.drawImage(img, 0, 0);
  const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
  applyChromaKey(imageData, settings);
  ctx.putImageData(imageData, 0, 0);
  return canvasToArrayBuffer(canvas);
}
async function processImageBuffer(buffer, mimeType, settings) {
  const blob = new Blob([buffer], { type: mimeType });
  const img = await loadImageFromBlob(blob);
  return processImageElement(img, settings);
}

// src/ui/chroma-modal.ts
var import_obsidian2 = require("obsidian");
var ChromaKeyModal = class extends import_obsidian2.Modal {
  constructor(app, file, defaults, onSubmit) {
    super(app);
    this.originalImageData = null;
    this.previewCtx = null;
    this.eyedropperActive = false;
    this.file = file;
    this.settings = { ...defaults };
    this.onSubmit = onSubmit;
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    this.setTitle("Remove background");
    const previewContainer = contentEl.createDiv({ cls: "chroma-preview-container" });
    this.previewCanvas = previewContainer.createEl("canvas", { cls: "chroma-preview-canvas" });
    this.previewCtx = this.previewCanvas.getContext("2d");
    this.setupCanvasClick();
    this.settingsContainer = contentEl.createDiv("settings-container");
    await this.loadImageData();
    this.renderSettings();
  }
  async loadImageData() {
    try {
      const buffer = await this.app.vault.readBinary(this.file);
      const mimeType = extensionToMime(this.file.extension);
      const blob = new Blob([buffer], { type: mimeType });
      const img = await loadImageFromBlob(blob);
      this.previewCanvas.width = img.width;
      this.previewCanvas.height = img.height;
      if (this.previewCtx) {
        this.previewCtx.drawImage(img, 0, 0);
        this.originalImageData = this.previewCtx.getImageData(0, 0, img.width, img.height);
      }
      this.updatePreview();
    } catch (error) {
      console.error("Failed to load image for preview", error);
    }
  }
  updatePreview() {
    if (!this.originalImageData || !this.previewCtx) return;
    const workingData = new ImageData(
      new Uint8ClampedArray(this.originalImageData.data),
      this.originalImageData.width,
      this.originalImageData.height
    );
    applyChromaKey(workingData, this.settings);
    this.previewCtx.putImageData(workingData, 0, 0);
  }
  setEyedropper(active) {
    this.eyedropperActive = active;
    this.previewCanvas.toggleClass("chroma-eyedropper-active", active);
  }
  setupCanvasClick() {
    this.previewCanvas.addEventListener("click", (event) => {
      if (!this.eyedropperActive || !this.originalImageData) return;
      const rect = this.previewCanvas.getBoundingClientRect();
      const scaleX = this.previewCanvas.width / rect.width;
      const scaleY = this.previewCanvas.height / rect.height;
      const x = Math.floor((event.clientX - rect.left) * scaleX);
      const y = Math.floor((event.clientY - rect.top) * scaleY);
      const index = (y * this.previewCanvas.width + x) * 4;
      const r = this.originalImageData.data[index];
      const g = this.originalImageData.data[index + 1];
      const b = this.originalImageData.data[index + 2];
      const hexColor = "#" + [r, g, b].map((v) => v.toString(16).padStart(2, "0")).join("").toUpperCase();
      this.settings.targetColor = hexColor;
      this.settings.autoDetectColor = false;
      this.setEyedropper(false);
      this.renderSettings();
      this.updatePreview();
    });
  }
  renderSettings() {
    this.settingsContainer.empty();
    new import_obsidian2.Setting(this.settingsContainer).setName("Auto-detect background color").setDesc("Sample the top-left pixel as the background color").addToggle(
      (toggle) => toggle.setValue(this.settings.autoDetectColor).onChange((value) => {
        this.settings.autoDetectColor = value;
        if (value) {
          this.setEyedropper(false);
        }
        this.updatePreview();
        this.renderSettings();
      })
    );
    if (!this.settings.autoDetectColor) {
      new import_obsidian2.Setting(this.settingsContainer).setName("Target color").setDesc("Hex color to remove, or use the eyedropper to pick from the image").addText(
        (text) => text.setPlaceholder("#Ffffff").setValue(this.settings.targetColor).onChange((value) => {
          const cleaned = value.trim();
          if (/^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$/.test(cleaned)) {
            this.settings.targetColor = cleaned;
            this.updatePreview();
          }
        })
      ).addButton(
        (btn) => btn.setIcon("pipette").setTooltip("Pick color from image").onClick(() => {
          this.setEyedropper(!this.eyedropperActive);
          btn.buttonEl.toggleClass("mod-cta", this.eyedropperActive);
        })
      );
    }
    new import_obsidian2.Setting(this.settingsContainer).setName("Edge softening").setDesc("Smooth alpha blending at background edges").addToggle(
      (toggle) => toggle.setValue(this.settings.edgeSoftening).onChange((value) => {
        this.settings.edgeSoftening = value;
        this.updatePreview();
      })
    );
    new import_obsidian2.Setting(this.settingsContainer).setName("Invert colors").setDesc("Invert colors of visible pixels (great for dark mode diagrams)").addToggle(
      (toggle) => toggle.setValue(this.settings.invertColors).onChange((value) => {
        this.settings.invertColors = value;
        this.updatePreview();
      })
    );
    new import_obsidian2.Setting(this.settingsContainer).setName("Tolerance").setDesc("Color distance threshold (0 = exact match, 100 = aggressive)").addSlider(
      (slider) => slider.setLimits(0, 100, 1).setValue(this.settings.tolerance).setDynamicTooltip().onChange((value) => {
        this.settings.tolerance = value;
        this.updatePreview();
      })
    );
    new import_obsidian2.Setting(this.settingsContainer).addButton(
      (btn) => btn.setButtonText("Process").setCta().onClick(() => {
        this.close();
        this.onSubmit({
          tolerance: this.settings.tolerance,
          autoDetectColor: this.settings.autoDetectColor,
          edgeSoftening: this.settings.edgeSoftening,
          invertColors: this.settings.invertColors,
          targetColor: this.settings.targetColor
        });
      })
    ).addButton(
      (btn) => btn.setButtonText("Cancel").onClick(() => {
        this.close();
      })
    );
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/main.ts
function extensionToMime(ext) {
  switch (ext.toLowerCase()) {
    case "png":
      return "image/png";
    case "jpg":
    case "jpeg":
      return "image/jpeg";
    case "gif":
      return "image/gif";
    case "bmp":
      return "image/bmp";
    case "webp":
      return "image/webp";
    default:
      return "image/png";
  }
}
var ChromaKeyPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new ChromaKeySettingTab(this.app, this));
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (!(file instanceof import_obsidian3.TFile)) return;
        if (!IMAGE_EXTENSIONS.includes(file.extension.toLowerCase())) return;
        menu.addItem((item) => {
          item.setTitle("Remove background").setIcon("image-minus").onClick(() => {
            this.openProcessingModal(file);
          });
        });
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        if (!(file instanceof import_obsidian3.TFolder)) return;
        if (oldPath !== this.settings.chromaFolderPath) return;
        this.settings.chromaFolderPath = file.path;
        void this.saveSettings();
      })
    );
    this.addCommand({
      id: "remove-background",
      name: "Remove background from image",
      checkCallback: (checking) => {
        const view = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
        if (!view) return false;
        const cursor = view.editor.getCursor();
        const line = view.editor.getLine(cursor.line);
        const imageName = this.extractImageEmbed(line);
        if (!imageName) return false;
        if (!checking) {
          const imageFile = this.app.metadataCache.getFirstLinkpathDest(
            imageName,
            view.file?.path ?? ""
          );
          if (imageFile) {
            this.openProcessingModal(imageFile);
          } else {
            new import_obsidian3.Notice(`Could not find image: ${imageName}`);
          }
        }
        return true;
      }
    });
  }
  /**
   * Extract image filename from an embed on a line, e.g. "![[photo.png]]" → "photo.png".
   * Returns null if no image embed is found.
   */
  extractImageEmbed(line) {
    const match = line.match(/!\[\[([^\]]+\.(png|jpe?g|gif|bmp|webp))\]\]/i);
    return match?.[1] ?? null;
  }
  openProcessingModal(sourceFile) {
    new ChromaKeyModal(this.app, sourceFile, this.settings, (result) => {
      const fullSettings = {
        ...result,
        chromaFolderPath: this.settings.chromaFolderPath
      };
      void this.processAndReplace(sourceFile, fullSettings);
    }).open();
  }
  /**
   * Process an image: remove background, save to chroma/ folder,
   * and replace the embed in the active editor.
   */
  async processAndReplace(sourceFile, settings) {
    new import_obsidian3.Notice("Processing image background\u2026");
    try {
      const buffer = await this.app.vault.readBinary(sourceFile);
      const mimeType = extensionToMime(sourceFile.extension);
      const processedBuffer = await processImageBuffer(buffer, mimeType, settings);
      const folderPath = this.settings.chromaFolderPath;
      const chromaFolder = this.app.vault.getAbstractFileByPath(folderPath);
      if (!chromaFolder) {
        await this.app.vault.createFolder(folderPath);
      }
      const baseName = sourceFile.basename;
      const dateString = (/* @__PURE__ */ new Date()).toISOString().replace(/[:.]/g, "-");
      const newFileName = `${baseName}-chroma-${dateString}.png`;
      const savePath = `${folderPath}/${newFileName}`;
      const newFile = await this.app.vault.createBinary(savePath, processedBuffer);
      const view = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
      if (view) {
        const editor = view.editor;
        const content = editor.getValue();
        const oldEmbed = `![[${sourceFile.name}]]`;
        const oldEmbedPath = `![[${sourceFile.path}]]`;
        const newEmbed = `![[${newFile.name}]]`;
        let updated = content;
        if (content.includes(oldEmbed)) {
          updated = content.replace(oldEmbed, newEmbed);
        } else if (content.includes(oldEmbedPath)) {
          updated = content.replace(oldEmbedPath, newEmbed);
        }
        if (updated !== content) {
          editor.setValue(updated);
        }
      }
      new import_obsidian3.Notice(`Background removed and saved to ${folderPath}/`);
    } catch (error) {
      console.error("Chroma Key Error:", error);
      new import_obsidian3.Notice("Failed to process image. Check the developer console for details.");
    }
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};


/* nosourcemap */